### ISSUE TITLE
Language Server Errors in SPARQL Code Cells 

### ISSUE THREAD

**Issue by BenjaminHofstetter** [zazuko/vscode-sparql-notebook#16]
SPARQL Code Cells throw an Language Server Error 
```
[Error - 10:28:17 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'getText')
  Code: -32603

**Comment by BenjaminHofstetter** [comment]
stardog issue: https://github.com/stardog-union/stardog-language-servers/issues/47
vscode issue: https://github.com/microsoft/vscode/issues/148384

**Comment by dbaeumer** [comment]
@BenjaminHofstetter how to you talk depend on the server?

**Comment by dbaeumer** [comment]
OK. I digged around a little and the problem is this:

https://github.com/stardog-union/stardog-vsc/blob/master/vscode-langserver-sparql/src/extension.ts#L40

The SPARQL language plugin explicitly defines that it only support `sparql` files that are stored on disk (e.g. have a file protocol). Notebook cells don't have a file scheme (since they are contained in a notebook ) and therefore the client doesn't sync them to the server. 

I don't know why they synced in former released but it was clearly not intended.

**Comment by ktk** [comment]
@dbaeumer thanks a lot for digging into it, if you are around Biel one day we happily offer a drink :)

**Comment by dbaeumer** [comment]
@ktk since I live in Zurich this might actually happen one day :-)

@ktk and @BenjaminHofstetter 

There will be a Developer Day tomorrow in the Circle in Zurich were we will host a VS Code Extension clinic. In case you are interested I can sent to an invite. But I would need your email address :-)
